# Generated by Django 3.0.4 on 2020-05-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='like',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
